
# Per the stackoverflow linked belo 
COL_NAME_MAX_LEN = 1000000

TEXT = "TEXT"
CHARACTER = TEXT
VARCHAR = TEXT
VARYING_CHARACTER = TEXT
NCHAR = TEXT
NATIVE_CHARACTER = TEXT
NVARCHAR = TEXT
CLOB = TEXT

INTEGER = "INTEGER"
INT = INTEGER
INTEGER = INTEGER
TINYINT = INTEGER
SMALLINT = INTEGER
MEDIUMINT = INTEGER
BIGINT = INTEGER
UNSIGNED_BIG_INT = INTEGER
INT2 = INTEGER
INT8 = INTEGER